# Generated by Django 5.0.1 on 2024-03-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
